# Automatically created with Minerva Node Editor
import threading
from Minerva import *

if __name__ == '__main__':
    Configuration.load_configuration("C:\\Users\\bruehle\\GitBAM\\Minerva\\Synthesis_Scripts\\Reaction_UiO_Example.json")

    # Containers
    reaction_flask_50_ml = Container(current_hardware='flaskstation', deck_position=0, slot_number=1, name='Reaction_Flask_50_mL', current_volume=None, max_volume=None, container_type=ContainerTypeCollection.FLASK_50_ML, has_stirbar=True, is_capped=False)
    zrocl2_container = Container(current_hardware='ot2_holder_15ml', deck_position=0, slot_number=1, name='ZrOCl2_Container', current_volume='15 mL', max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_15_ML, has_stirbar=False, is_capped=False)
    dmf_container_falcon_tube = Container(current_hardware='ot2_holder_15ml', deck_position=0, slot_number=2, name='DMF_Container_Falcon_Tube', current_volume='15 mL', max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_15_ML, has_stirbar=False, is_capped=False)
    acetic_acid_container = Container(current_hardware='ot2_holder_15ml', deck_position=0, slot_number=3, name='Acetic_Acid_Container', current_volume='15 mL', max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_15_ML, has_stirbar=False, is_capped=False)
    dap_container = Container(current_hardware='ot2_holder_15ml', deck_position=0, slot_number=4, name='DAP_Container', current_volume='15 mL', max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_15_ML, has_stirbar=False, is_capped=False)
    dmf_container = Container(current_hardware='valve1', deck_position=0, slot_number=8, name='DMF_Container', current_volume='500 mL', max_volume='500 mL', container_type=None, has_stirbar=False, is_capped=False)
    dcm_container = Container(current_hardware='valve1', deck_position=0, slot_number=9, name='DCM_Container', current_volume='500 mL', max_volume='500 mL', container_type=None, has_stirbar=False, is_capped=False)
    centrifuge_tube_50ml = Container(current_hardware='falcon_tube_holder_50mL', deck_position=0, slot_number=1, name='Centrifuge_Tube_50mL', current_volume=None, max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_50_ML, has_stirbar=False, is_capped=True)
    centrifuge_tube_50ml_counterweight = Container(current_hardware='falcon_tube_holder_50mL', deck_position=0, slot_number=1, name='Centrifuge_Tube_50mL_Counterweight', current_volume=None, max_volume=None, container_type=ContainerTypeCollection.FALCON_TUBE_50_ML, has_stirbar=False, is_capped=True)
    waste_container_valve1 = Container(current_hardware='valve1', deck_position=0, slot_number=0, name='waste_container_valve1', current_volume=None, max_volume=None, container_type=None, has_stirbar=False, is_capped=False)

    # Chemicals
    chemical_zrocl28_h2o = Chemical(container=zrocl2_container, lookup_missing_values=True, name='ZrOCl28 H2O', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass='0.028 g', molar_amount='0.086 mmol', concentration=None, mass_concentration='10 mg/mL', volume=None, is_stock_solution=False)
    chemical_dmf = Chemical(container=dmf_container_falcon_tube, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='5.0 mL', is_stock_solution=False)
    chemical_acetic_acid = Chemical(container=acetic_acid_container, lookup_missing_values=True, name='acetic acid', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount='17.0 mmol', concentration=None, mass_concentration=None, volume='980.0 uL', is_stock_solution=False)
    chemical_4_4_anthracene_9_10_diyldibenzoic_acid = Chemical(container=dap_container, lookup_missing_values=True, name='4,4-(anthracene-9,10-diyl)dibenzoic acid', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass='0.036 g', molar_amount='0.086 mmol', concentration=None, mass_concentration='10 mg/mL', volume=None, is_stock_solution=False)
    chemical_dmf_1 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_dmf_2 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_dmf_3 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_dmf_4 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_dmf_5 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_dmf_6 = Chemical(container=dmf_container, lookup_missing_values=True, name='DMF', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)
    chemical_ch2cl2 = Chemical(container=dcm_container, lookup_missing_values=True, name='CH2Cl2', lot_number='', supplier='', cas='', smiles='', density=None, molar_mass=None, mass=None, molar_amount=None, concentration=None, mass_concentration=None, volume='30.0 mL', is_stock_solution=False)

    # Reactions
    def reaction_0():
        reaction_flask_50_ml.add_chemical(chemical=chemical_zrocl28_h2o, withdraw_rate=None, addition_rate=None, robot_arm=None, capper_decapper=None, return_container_after_addition=False, return_chemicals_after_addition=True, bottom_clearance=None, purging_volume='30mL', purging_addition_rate=None, purging_port=None, priming_volume=None, priming_waste_container=None)
        reaction_flask_50_ml.add_chemical(chemical=chemical_dmf, withdraw_rate=None, addition_rate=None, robot_arm=None, capper_decapper=None, return_container_after_addition=False, return_chemicals_after_addition=True, bottom_clearance=None, purging_volume='30mL', purging_addition_rate=None, purging_port=None, priming_volume=None, priming_waste_container=None)
        reaction_flask_50_ml.heat(heating_temperature='25.0 C', stirring_speed='400.0 rpm', heating_time='5.0 min', temperature_stabilization_time='5min', maximum_temperature_deviation='2C', cooldown_temperature='40C', active_cooling=True, temperature_sensor='EXTERNAL', robot_arm=None)
        reaction_flask_50_ml.sonicate(sonicator=None, sonication_time='10.0 min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', bottom_clearance=None, container_for_cleaning=None, robot_arm=None, capper_decapper=None)
        reaction_flask_50_ml.add_chemical(chemical=[chemical_acetic_acid, chemical_4_4_anthracene_9_10_diyldibenzoic_acid], withdraw_rate=None, addition_rate=None, robot_arm=None, capper_decapper=None, return_container_after_addition=False, return_chemicals_after_addition=True, bottom_clearance=None, purging_volume='30mL', purging_addition_rate=None, purging_port=None, priming_volume=None, priming_waste_container=None)
        reaction_flask_50_ml.heat(heating_temperature='120.0 C', stirring_speed='300.0 rpm', heating_time='24.0 h', temperature_stabilization_time='5min', maximum_temperature_deviation='2C', cooldown_temperature='40C', active_cooling=True, temperature_sensor='EXTERNAL', robot_arm=None)
        reaction_flask_50_ml.heat(heating_temperature='25.0 C', stirring_speed='300.0 rpm', heating_time='5.0 min', temperature_stabilization_time='5min', maximum_temperature_deviation='2C', cooldown_temperature='40C', active_cooling=True, temperature_sensor='EXTERNAL', robot_arm=None)
        reaction_flask_50_ml.centrifuge(containers=[centrifuge_tube_50ml, centrifuge_tube_50ml_counterweight], centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_dmf, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)
        centrifuge_tube_50ml.remove_supernatant_and_redisperse(waste_container=waste_container_valve1, redispersion_chemical=chemical_ch2cl2, sonicator=None, sonication_time='10min', sonication_power=50.0, sonication_amplitude=50.0, sonication_temperature='20C', container_for_cleaning=None, robot_arm=None, capper_decapper=None, purging_volume='30mL', bottom_clearance_withdrawing=None, bottom_clearance_dispensing=None, bottom_clearance_sonication=None)
        centrifuge_tube_50ml.centrifuge(containers=centrifuge_tube_50ml_counterweight, centrifugation_speed='8000.0 rpm', centrifugation_time='15.0 min', centrifugation_temperature='25.0 C', bottom_clearance_withdrawing=3.0, dropoff_location=None, robot_arm=None, centrifuge=None, transfer_hardware=None, capper_decapper=None)


    # Start reactions in individual threads
    reaction_thread_0 = threading.Thread(target=reaction_0)
    reaction_thread_0.start()

    # Wait for all threads to finish
    reaction_thread_0.join()
